<?php

return array(
  'utmaltor_domains' => array(
    'group_name' => 'UTMaltor Preferences',
    'group' => 'utmaltor',
    'name' => 'utmaltor_domains',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'default' => '',
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['utmaltor' => ['weight' => 10]],
    'title' => 'List of domains separate by pipe |',
    'description' => 'List of domains separate by pipe |',
    'help_text' => 'List of domains separate by pipe |',
  ),
  'utmaltor_source' => array(
    'group_name' => 'UTMaltor Preferences',
    'group' => 'utmaltor',
    'name' => 'utmaltor_source',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'default' => 'civimail',
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['utmaltor' => ['weight' => 20]],
    'title' => 'Smarty template for utm_source field',
    'description' => 'Smarty template for utm_source field',
    'help_text' => 'Smarty template for utm_source field',
  ),
  'utmaltor_medium' => array(
    'group_name' => 'UTMaltor Preferences',
    'group' => 'utmaltor',
    'name' => 'utmaltor_medium',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'default' => 'email',
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['utmaltor' => ['weight' => 30]],
    'title' => 'Smarty template for utm_medium field',
    'description' => 'Smarty template for utm_medium field',
    'help_text' => 'Smarty template for utm_medium field',
  ),
  'utmaltor_campaign' => array(
    'group_name' => 'UTMaltor Preferences',
    'group' => 'utmaltor',
    'name' => 'utmaltor_campaign',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'default' => '{$date}',
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['utmaltor' => ['weight' => 40]],
    'title' => 'Smarty template for utm_campaign field',
    'description' => 'Smarty template for utm_campaign field',
    'help_text' => 'Smarty template for utm_campaign field',
  ),
  'utmaltor_source_override' => array(
    'group_name' => 'UTMaltor Preferences',
    'group' => 'utmaltor',
    'name' => 'utmaltor_source_override',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => 1,
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['utmaltor' => ['weight' => 50]],
    'title' => 'Override existing utm_source params',
    'description' => "Override existing utm_source params",
    'help_text' => "Override existing utm_source params",
  ),
  'utmaltor_medium_override' => array(
    'group_name' => 'UTMaltor Preferences',
    'group' => 'utmaltor',
    'name' => 'utmaltor_medium_override',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => 1,
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['utmaltor' => ['weight' => 60]],
    'title' => 'Override existing utm_medium params',
    'description' => 'Override existing utm_medium params',
    'help_text' => 'Override existing utm_medium params',
  ),
  'utmaltor_campaign_override' => array(
    'group_name' => 'UTMaltor Preferences',
    'group' => 'utmaltor',
    'name' => 'utmaltor_campaign_override',
    'type' => 'Boolean',
    'quick_form_type' => 'YesNo',
    'default' => 1,
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'settings_pages' => ['utmaltor' => ['weight' => 70]],
    'title' => 'Override existing utm_campaign params',
    'description' => 'Override existing utm_campaign params',
    'help_text' => 'Override existing utm_campaign params',
  ),
);
